Oc 98 update design for demo
OrdinaNederland/one-community pull request #53
Opened 2022-02-10 08:24 UTC by dennis-ordina

2022-02-10 09:08 UTC, vasili-ordina requested changes
zoals gezegd even deze aanpassen:

100 – Thin.
200 – Extra Light (Ultra Light)
300 – Light.
400 – Normal.
500 – Medium.
600 – Semi Bold (Demi Bold)
700 – Bold.
800 – Extra Bold (Ultra Bold)

verder lijkt het me goed

2022-02-10 09:08 UTC, vasili-ordina commented on frontend/assets/scss/variables.scss
> +  font-weight: 200;
Moet font-weight: 400 zijn.

2022-02-10 09:08 UTC, vasili-ordina commented on frontend/assets/scss/variables.scss
> +  font-weight: 200;
deze ook font-weight: 400

2022-02-10 09:08 UTC, vasili-ordina commented on frontend/assets/scss/variables.scss
>  }
these are the font-weights to be used:
100 – Thin.
200 – Extra Light (Ultra Light)
300 – Light.
400 – Normal.
500 – Medium.
600 – Semi Bold (Demi Bold)
700 – Bold.
800 – Extra Bold (Ultra Bold)

2022-02-10 10:17 UTC, vasili-ordina commented on frontend/components/layout/TheHeader.vue
> +    height: 5rem;
is dit het logo? ik kan in de interface niet terugvinden waar deze styling anders over gaat.
if so: logo niet in rem! leg ik wel uit als we in call zitten. Hij mag ook iets groter ;)

2022-02-10 10:17 UTC, vasili-ordina commented on frontend/pages/about.vue
> -        <div class="about-us__content">
Als je eens tijd over hebt, voor de volgende keer, kijk dan eens naar HTML5 tags. Het zijn tags zoals "article", "header" en "section". Ze geven meer semantiek aan je document dan die eindeloze div-tags. ;)

2022-02-10 14:36 UTC, dennis-ordina commented on frontend/pages/about.vue
> -        <div class="about-us__content">
Goeie, welke zou je hier adviseren bijvoorbeeld? Ik heb vlak erboven al section gebruikt.

2022-02-15 15:42 UTC, DrKlonk reviewed
Ik krijg ook nog een warning (iets in mijn assets) en een ts-error als in `npm run dev` draai. Kan je die ook fixen?

2022-02-15 15:42 UTC, DrKlonk commented on frontend/components/base/BaseButtonNew.vue
> +      this.$router.push({
Dit is bij mij kaduuk op ts typing voor `this`

2022-02-15 15:42 UTC, DrKlonk commented on frontend/components/base/BaseButtonNew.vue
> +      this.$router.push({
Ik denk dat het handiger is om er NuxtLinks van te maken

2022-02-15 15:55 UTC, DrKlonk commented on frontend/pages/about.vue
> +            <template v-slot:title>Start mobbing* together</template>
Waarom de "*"?

2022-02-16 09:26 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
>  <template>
Ik heb hem een andere naam gegeven en het oude font op de BaseButton vervangen

2022-02-16 09:35 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
> -      validator(value: string) {
Ik heb het weer teruggedraaid

2022-02-16 10:38 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
> +    @click="navigateTo"
required false gemaakt zodat de button optioneel gebruikt kan worden om te navigeren

2022-02-16 10:52 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
> +@media (max-width: 850px) {
Coole artikelen over rem en em! Heb de queries aangepast door em te gebruiken.

2022-02-16 10:55 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
> +    :class="`${buttonColor} responsive-${isResponsive}`"
Als `responsive-true` dan veranderd de button om er mooi uit te blijven zien op een article card. Dit gedrag wil je niet bij een button die niet op die card zit.

2022-02-16 10:56 UTC, dennis-ordina commented on frontend/components/layout/TheHeader.vue
> +    height: 130px;
Ja, Vasili had hier een hele goeie reden voor, alleen die heb ik nog niet gehoord :p

2022-02-16 13:26 UTC, dennis-ordina commented on frontend/components/layout/TheHeader.vue
> +  // width: $header-item-width;
yes

2022-02-16 13:37 UTC, dennis-ordina commented on frontend/components/layout/TheHeader.vue
> +        name: 'Connect',
De naam Connect komt uit de opzet van de MVP. Wat er precies met die pagina moet gebeuren staat ter discussie vandaar dat die nu maar naar het contact formulier gaat.

2022-02-16 13:43 UTC, dennis-ordina commented on frontend/pages/about.vue
> +          <BaseActionCard
Hmm goeie inderdaad! Maakt de html een stuk leesbaarder.

2022-02-16 13:54 UTC, dennis-ordina commented on frontend/components/base/BaseButtonNew.vue
> +    isResponsive: {
Dient wel een doel voor de actionCard

2022-02-16 14:06 UTC, dennis-ordina commented on frontend/components/base/BaseActionCard.vue
> +  min-height: 30rem;
ja klopt. hier zat ik een tijdje mee te klooien, maar gewoon height werkt prima nu!

2022-02-16 14:12 UTC, dennis-ordina commented on frontend/components/base/BaseActionCard.vue
> +@media (max-width: 900px) {
Hoop weggehaald inderdaad.

2022-02-16 14:12 UTC, dennis-ordina commented on frontend/pages/about.vue
> +            <template v-slot:title>Start mobbing* together</template>
In het design van Vasili stond nog een uitleg over mobbing onderaan de card. Die heb ik weggelaten en het sterretje dus ook verwijderd.

2022-02-21 09:01 UTC, DrKlonk reviewed
Nog 2 dingen:

Bij mij is het in de assets Logo.svg, maar in TheHeader.vue logo.svg. Kan je dat aanpassen?
![image](https://user-images.githubusercontent.com/6998380/154921885-169c26d0-0388-4953-9545-c615e4a81e0d.png)

En er staan nog op een paar plekken verwijzingen naar Roboto. Kan je dat ctrl-f'en en wegpoetsen?

2022-02-21 14:48 UTC, dennis-ordina commented on frontend/components/global/OutlineButton.vue
> +    :class="`${color} responsive-${isResponsive}`"
Ik heb deze button nu echt een button gemaakt en de resoponsive class en navRoute weggesloopt. Alle links die deze button gebruikte heb ik in anchors met 'button-like' styling veranderd.

2022-02-22 11:02 UTC, DrKlonk commented on frontend/layouts/default.vue
> +  &.outline-button-link {
Ter info: Voor mij was het prima geweest als je de `<button>` in OutlineButton.vue had vervangen door een `<a>`, met bijbehorende wijzigingen. Het ging me meer om de semantiek in de HTML. Dit kan natuurlijk ook

2022-02-22 11:02 UTC, DrKlonk commented on frontend/components/global/OutlineButton.vue
>  <template>
Deze leeft nu nog in de LoginBox.vue. Is dat bewust?

2022-02-22 12:45 UTC, dennis-ordina commented on frontend/components/global/OutlineButton.vue
>  <template>
Ja, want hier is het echt een button en geen anchor

2022-02-22 13:08 UTC, DrKlonk commented on frontend/components/global/OutlineButton.vue
>  <template>
Ben ik het niet mee eens, profile lijkt me een link naar profile. Het zit ook in een NuxtLink en dat is een `<a>`. En een `<button>` in een `<a>` is semantisch niet ok. Dit zijn overigens overblijfselen van een eerdere discussie, die ik met Jolissa had. Ik heb [deze](https://one-community.atlassian.net/browse/OC-129) nu aangemaakt en voor nu laten we het er dan bij

2022-02-22 13:09 UTC, DrKlonk approved these changes

2022-02-22 14:25 UTC, merged